source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
use_frameworks!

target 'AFNetworkingWithMantle' do
    pod 'AFNetworking', '2.5.4'
    pod 'SVProgressHUD', '1.1.3'
    pod 'MBProgressHUD', '~> 0.8'
    pod 'Reachability', '3.1.1'   
    pod 'Mantle', '1.5'
end


